import cv2

__all__ = ["template_dict", "template_image_dict", "masks"]


template_dict = {
    "lock": {
        # used in lock or not
        # "./templates/lock/mystic/lock.png": {'lock': True, 'type': 'mystic'},
        # "./templates/lock/mystic/unlock.png": {'lock': False, 'type': 'mystic'},
        # "./templates/lock/normal/lock.png": {'lock': True, 'type': 'normal'},
        # "./templates/lock/normal/unlock.png": {'lock': False, 'type': 'normal'},
        # "./templates/lock/relic/lock.png": {'lock': True, 'type': 'relic'},
        # "./templates/lock/relic/unlock.png": {'lock': False, 'type': 'relic'},
        # "./templates/lock/replica/lock.png": {'lock': True, 'type': 'replica'},
        # "./templates/lock/replica/unlock.png": {'lock': False, 'type': 'replica'},
        "./templates/lock/mystic/lock.png": {"lock": True},
        "./templates/lock/mystic/unlock.png": {"lock": False},
        "./templates/lock/normal/lock.png": {"lock": True},
        "./templates/lock/normal/unlock.png": {"lock": False},
        "./templates/lock/relic/lock.png": {"lock": True},
        "./templates/lock/relic/unlock.png": {"lock": False},
        "./templates/lock/replica/lock.png": {"lock": True},
        "./templates/lock/replica/unlock.png": {"lock": False},
    },
    "reinforce": {
        "./templates/reinforce/mystic/0.png": {"reinforce": "+0", "type": "mystic"},
        "./templates/reinforce/mystic/1.png": {"reinforce": "+1", "type": "mystic"},
        "./templates/reinforce/mystic/10.png": {"reinforce": "+10", "type": "mystic"},
        "./templates/reinforce/mystic/11.png": {"reinforce": "+11", "type": "mystic"},
        "./templates/reinforce/mystic/12.png": {"reinforce": "+12", "type": "mystic"},
        "./templates/reinforce/mystic/13.png": {"reinforce": "+13", "type": "mystic"},
        "./templates/reinforce/mystic/14.png": {"reinforce": "+14", "type": "mystic"},
        "./templates/reinforce/mystic/15.png": {"reinforce": "+15", "type": "mystic"},
        "./templates/reinforce/mystic/2.png": {"reinforce": "+2", "type": "mystic"},
        "./templates/reinforce/mystic/3.png": {"reinforce": "+3", "type": "mystic"},
        "./templates/reinforce/mystic/4.png": {"reinforce": "+4", "type": "mystic"},
        "./templates/reinforce/mystic/5.png": {"reinforce": "+5", "type": "mystic"},
        "./templates/reinforce/mystic/6.png": {"reinforce": "+6", "type": "mystic"},
        "./templates/reinforce/mystic/7.png": {"reinforce": "+7", "type": "mystic"},
        "./templates/reinforce/mystic/8.png": {"reinforce": "+8", "type": "mystic"},
        "./templates/reinforce/mystic/9.png": {"reinforce": "+9", "type": "mystic"},
        "./templates/reinforce/normal/0.png": {"reinforce": "+0", "type": "normal"},
        "./templates/reinforce/normal/1.png": {"reinforce": "+1", "type": "normal"},
        "./templates/reinforce/normal/10.png": {"reinforce": "+10", "type": "normal"},
        "./templates/reinforce/normal/11.png": {"reinforce": "+11", "type": "normal"},
        "./templates/reinforce/normal/12.png": {"reinforce": "+12", "type": "normal"},
        "./templates/reinforce/normal/13.png": {"reinforce": "+13", "type": "normal"},
        "./templates/reinforce/normal/14.png": {"reinforce": "+14", "type": "normal"},
        "./templates/reinforce/normal/15.png": {"reinforce": "+15", "type": "normal"},
        "./templates/reinforce/normal/2.png": {"reinforce": "+2", "type": "normal"},
        "./templates/reinforce/normal/3.png": {"reinforce": "+3", "type": "normal"},
        "./templates/reinforce/normal/4.png": {"reinforce": "+4", "type": "normal"},
        "./templates/reinforce/normal/5.png": {"reinforce": "+5", "type": "normal"},
        "./templates/reinforce/normal/6.png": {"reinforce": "+6", "type": "normal"},
        "./templates/reinforce/normal/7.png": {"reinforce": "+7", "type": "normal"},
        "./templates/reinforce/normal/8.png": {"reinforce": "+8", "type": "normal"},
        "./templates/reinforce/normal/9.png": {"reinforce": "+9", "type": "normal"},
        "./templates/reinforce/relic/0.png": {"reinforce": "+0", "type": "relic"},
        "./templates/reinforce/relic/1.png": {"reinforce": "+1", "type": "relic"},
        "./templates/reinforce/relic/10.png": {"reinforce": "+10", "type": "relic"},
        "./templates/reinforce/relic/11.png": {"reinforce": "+11", "type": "relic"},
        "./templates/reinforce/relic/12.png": {"reinforce": "+12", "type": "relic"},
        "./templates/reinforce/relic/13.png": {"reinforce": "+13", "type": "relic"},
        "./templates/reinforce/relic/14.png": {"reinforce": "+14", "type": "relic"},
        "./templates/reinforce/relic/15.png": {"reinforce": "+15", "type": "relic"},
        "./templates/reinforce/relic/2.png": {"reinforce": "+2", "type": "relic"},
        "./templates/reinforce/relic/3.png": {"reinforce": "+3", "type": "relic"},
        "./templates/reinforce/relic/4.png": {"reinforce": "+4", "type": "relic"},
        "./templates/reinforce/relic/5.png": {"reinforce": "+5", "type": "relic"},
        "./templates/reinforce/relic/6.png": {"reinforce": "+6", "type": "relic"},
        "./templates/reinforce/relic/7.png": {"reinforce": "+7", "type": "relic"},
        "./templates/reinforce/relic/8.png": {"reinforce": "+8", "type": "relic"},
        "./templates/reinforce/relic/9.png": {"reinforce": "+9", "type": "relic"},
        "./templates/reinforce/replica/0.png": {"reinforce": "+0", "type": "replica"},
        "./templates/reinforce/replica/1.png": {"reinforce": "+1", "type": "replica"},
        "./templates/reinforce/replica/10.png": {"reinforce": "+10", "type": "replica"},
        "./templates/reinforce/replica/11.png": {"reinforce": "+11", "type": "replica"},
        "./templates/reinforce/replica/12.png": {"reinforce": "+12", "type": "replica"},
        "./templates/reinforce/replica/13.png": {"reinforce": "+13", "type": "replica"},
        "./templates/reinforce/replica/14.png": {"reinforce": "+14", "type": "replica"},
        "./templates/reinforce/replica/15.png": {"reinforce": "+15", "type": "replica"},
        "./templates/reinforce/replica/2.png": {"reinforce": "+2", "type": "replica"},
        "./templates/reinforce/replica/3.png": {"reinforce": "+3", "type": "replica"},
        "./templates/reinforce/replica/4.png": {"reinforce": "+4", "type": "replica"},
        "./templates/reinforce/replica/5.png": {"reinforce": "+5", "type": "replica"},
        "./templates/reinforce/replica/6.png": {"reinforce": "+6", "type": "replica"},
        "./templates/reinforce/replica/7.png": {"reinforce": "+7", "type": "replica"},
        "./templates/reinforce/replica/8.png": {"reinforce": "+8", "type": "replica"},
        "./templates/reinforce/replica/9.png": {"reinforce": "+9", "type": "replica"},
    },
    "part_icon": {
        "./templates/part/icon/body.png": {"part": "body"},
        "./templates/part/icon/foot.png": {"part": "foot"},
        "./templates/part/icon/hand.png": {"part": "hand"},
        "./templates/part/icon/neck.png": {"part": "neck"},
        "./templates/part/icon/ring.png": {"part": "ring"},
        "./templates/part/icon/weapon.png": {"part": "weapon"},
    },
    "part_set": {
        "./templates/part/set/aegis.png": {"set": "aegis"},
        "./templates/part/set/amplify.png": {"set": "amplify"},
        "./templates/part/set/berserk.png": {"set": "berserk"},
        "./templates/part/set/blessing.png": {"set": "blessing"},
        "./templates/part/set/bulwark.png": {"set": "bulwark"},
        "./templates/part/set/charge.png": {"set": "charge"},
        "./templates/part/set/command.png": {"set": "command"},
        "./templates/part/set/defense.png": {"set": "defense"},
        "./templates/part/set/efficacy.png": {"set": "efficacy"},
        "./templates/part/set/frenzy.png": {"set": "frenzy"},
        "./templates/part/set/haste.png": {"set": "haste"},
        "./templates/part/set/healing.png": {"set": "healing"},
        "./templates/part/set/leech.png": {"set": "leech"},
        "./templates/part/set/life.png": {"set": "life"},
        "./templates/part/set/morale.png": {"set": "morale"},
        "./templates/part/set/pierce.png": {"set": "pierce"},
        "./templates/part/set/precision.png": {"set": "precision"},
        "./templates/part/set/resolve.png": {"set": "resolve"},
        "./templates/part/set/revenge.png": {"set": "revenge"},
        "./templates/part/set/shock.png": {"set": "shock"},
        "./templates/part/set/strength.png": {"set": "strength"},
        "./templates/part/set/vengeful.png": {"set": "vengeful"},
        "./templates/part/set/zeal.png": {"set": "zeal"},
    },
    "option_num": {
        "./templates/suboption/num/0.png": "0",
        "./templates/suboption/num/1.png": "1",
        "./templates/suboption/num/2.png": "2",
        "./templates/suboption/num/3.png": "3",
        "./templates/suboption/num/4.png": "4",
        "./templates/suboption/num/5.png": "5",
        "./templates/suboption/num/6.png": "6",
        "./templates/suboption/num/7.png": "7",
        "./templates/suboption/num/8.png": "8",
        "./templates/suboption/num/9.png": "9",
        "./templates/suboption/num/percent.png": "%",
    },
    "option_text": {
        "./templates/suboption/text/attack.png": "attack",
        "./templates/suboption/text/defence.png": "defence",
        "./templates/suboption/text/speed.png": "speed",
        "./templates/suboption/text/resist.png": "resist",
        "./templates/suboption/text/hit.png": "hit",
        "./templates/suboption/text/health.png": "health",
        "./templates/suboption/text/crit.png": "crit",
        "./templates/suboption/text/damage.png": "damage",
        "./templates/suboption/text/chance.png": "chance",
        "./templates/suboption/text/effect.png": "effect",
    },
}

template_image_dict = {
    "./templates/lock/mystic/lock.png": cv2.imread("./templates/lock/mystic/lock.png"),
    "./templates/lock/mystic/unlock.png": cv2.imread("./templates/lock/mystic/unlock.png"),
    "./templates/lock/normal/lock.png": cv2.imread("./templates/lock/normal/lock.png"),
    "./templates/lock/normal/unlock.png": cv2.imread("./templates/lock/normal/unlock.png"),
    "./templates/lock/relic/lock.png": cv2.imread("./templates/lock/relic/lock.png"),
    "./templates/lock/relic/unlock.png": cv2.imread("./templates/lock/relic/unlock.png"),
    "./templates/lock/replica/lock.png": cv2.imread("./templates/lock/replica/lock.png"),
    "./templates/lock/replica/unlock.png": cv2.imread("./templates/lock/replica/unlock.png"),
    "./templates/reinforce/mystic/0.png": cv2.imread("./templates/reinforce/mystic/0.png"),
    "./templates/reinforce/mystic/1.png": cv2.imread("./templates/reinforce/mystic/1.png"),
    "./templates/reinforce/mystic/10.png": cv2.imread("./templates/reinforce/mystic/10.png"),
    "./templates/reinforce/mystic/11.png": cv2.imread("./templates/reinforce/mystic/11.png"),
    "./templates/reinforce/mystic/12.png": cv2.imread("./templates/reinforce/mystic/12.png"),
    "./templates/reinforce/mystic/13.png": cv2.imread("./templates/reinforce/mystic/13.png"),
    "./templates/reinforce/mystic/14.png": cv2.imread("./templates/reinforce/mystic/14.png"),
    "./templates/reinforce/mystic/15.png": cv2.imread("./templates/reinforce/mystic/15.png"),
    "./templates/reinforce/mystic/2.png": cv2.imread("./templates/reinforce/mystic/2.png"),
    "./templates/reinforce/mystic/3.png": cv2.imread("./templates/reinforce/mystic/3.png"),
    "./templates/reinforce/mystic/4.png": cv2.imread("./templates/reinforce/mystic/4.png"),
    "./templates/reinforce/mystic/5.png": cv2.imread("./templates/reinforce/mystic/5.png"),
    "./templates/reinforce/mystic/6.png": cv2.imread("./templates/reinforce/mystic/6.png"),
    "./templates/reinforce/mystic/7.png": cv2.imread("./templates/reinforce/mystic/7.png"),
    "./templates/reinforce/mystic/8.png": cv2.imread("./templates/reinforce/mystic/8.png"),
    "./templates/reinforce/mystic/9.png": cv2.imread("./templates/reinforce/mystic/9.png"),
    "./templates/reinforce/normal/0.png": cv2.imread("./templates/reinforce/normal/0.png"),
    "./templates/reinforce/normal/1.png": cv2.imread("./templates/reinforce/normal/1.png"),
    "./templates/reinforce/normal/10.png": cv2.imread("./templates/reinforce/normal/10.png"),
    "./templates/reinforce/normal/11.png": cv2.imread("./templates/reinforce/normal/11.png"),
    "./templates/reinforce/normal/12.png": cv2.imread("./templates/reinforce/normal/12.png"),
    "./templates/reinforce/normal/13.png": cv2.imread("./templates/reinforce/normal/13.png"),
    "./templates/reinforce/normal/14.png": cv2.imread("./templates/reinforce/normal/14.png"),
    "./templates/reinforce/normal/15.png": cv2.imread("./templates/reinforce/normal/15.png"),
    "./templates/reinforce/normal/2.png": cv2.imread("./templates/reinforce/normal/2.png"),
    "./templates/reinforce/normal/3.png": cv2.imread("./templates/reinforce/normal/3.png"),
    "./templates/reinforce/normal/4.png": cv2.imread("./templates/reinforce/normal/4.png"),
    "./templates/reinforce/normal/5.png": cv2.imread("./templates/reinforce/normal/5.png"),
    "./templates/reinforce/normal/6.png": cv2.imread("./templates/reinforce/normal/6.png"),
    "./templates/reinforce/normal/7.png": cv2.imread("./templates/reinforce/normal/7.png"),
    "./templates/reinforce/normal/8.png": cv2.imread("./templates/reinforce/normal/8.png"),
    "./templates/reinforce/normal/9.png": cv2.imread("./templates/reinforce/normal/9.png"),
    "./templates/reinforce/relic/0.png": cv2.imread("./templates/reinforce/relic/0.png"),
    "./templates/reinforce/relic/1.png": cv2.imread("./templates/reinforce/relic/1.png"),
    "./templates/reinforce/relic/10.png": cv2.imread("./templates/reinforce/relic/10.png"),
    "./templates/reinforce/relic/11.png": cv2.imread("./templates/reinforce/relic/11.png"),
    "./templates/reinforce/relic/12.png": cv2.imread("./templates/reinforce/relic/12.png"),
    "./templates/reinforce/relic/13.png": cv2.imread("./templates/reinforce/relic/13.png"),
    "./templates/reinforce/relic/14.png": cv2.imread("./templates/reinforce/relic/14.png"),
    "./templates/reinforce/relic/15.png": cv2.imread("./templates/reinforce/relic/15.png"),
    "./templates/reinforce/relic/2.png": cv2.imread("./templates/reinforce/relic/2.png"),
    "./templates/reinforce/relic/3.png": cv2.imread("./templates/reinforce/relic/3.png"),
    "./templates/reinforce/relic/4.png": cv2.imread("./templates/reinforce/relic/4.png"),
    "./templates/reinforce/relic/5.png": cv2.imread("./templates/reinforce/relic/5.png"),
    "./templates/reinforce/relic/6.png": cv2.imread("./templates/reinforce/relic/6.png"),
    "./templates/reinforce/relic/7.png": cv2.imread("./templates/reinforce/relic/7.png"),
    "./templates/reinforce/relic/8.png": cv2.imread("./templates/reinforce/relic/8.png"),
    "./templates/reinforce/relic/9.png": cv2.imread("./templates/reinforce/relic/9.png"),
    "./templates/reinforce/replica/0.png": cv2.imread("./templates/reinforce/replica/0.png"),
    "./templates/reinforce/replica/1.png": cv2.imread("./templates/reinforce/replica/1.png"),
    "./templates/reinforce/replica/10.png": cv2.imread("./templates/reinforce/replica/10.png"),
    "./templates/reinforce/replica/11.png": cv2.imread("./templates/reinforce/replica/11.png"),
    "./templates/reinforce/replica/12.png": cv2.imread("./templates/reinforce/replica/12.png"),
    "./templates/reinforce/replica/13.png": cv2.imread("./templates/reinforce/replica/13.png"),
    "./templates/reinforce/replica/14.png": cv2.imread("./templates/reinforce/replica/14.png"),
    "./templates/reinforce/replica/15.png": cv2.imread("./templates/reinforce/replica/15.png"),
    "./templates/reinforce/replica/2.png": cv2.imread("./templates/reinforce/replica/2.png"),
    "./templates/reinforce/replica/3.png": cv2.imread("./templates/reinforce/replica/3.png"),
    "./templates/reinforce/replica/4.png": cv2.imread("./templates/reinforce/replica/4.png"),
    "./templates/reinforce/replica/5.png": cv2.imread("./templates/reinforce/replica/5.png"),
    "./templates/reinforce/replica/6.png": cv2.imread("./templates/reinforce/replica/6.png"),
    "./templates/reinforce/replica/7.png": cv2.imread("./templates/reinforce/replica/7.png"),
    "./templates/reinforce/replica/8.png": cv2.imread("./templates/reinforce/replica/8.png"),
    "./templates/reinforce/replica/9.png": cv2.imread("./templates/reinforce/replica/9.png"),
    "./templates/part/icon/body.png": cv2.imread("./templates/part/icon/body.png"),
    "./templates/part/icon/foot.png": cv2.imread("./templates/part/icon/foot.png"),
    "./templates/part/icon/hand.png": cv2.imread("./templates/part/icon/hand.png"),
    "./templates/part/icon/neck.png": cv2.imread("./templates/part/icon/neck.png"),
    "./templates/part/icon/ring.png": cv2.imread("./templates/part/icon/ring.png"),
    "./templates/part/icon/weapon.png": cv2.imread("./templates/part/icon/weapon.png"),
    "./templates/part/set/aegis.png": cv2.imread("./templates/part/set/aegis.png"),
    "./templates/part/set/amplify.png": cv2.imread("./templates/part/set/amplify.png"),
    "./templates/part/set/berserk.png": cv2.imread("./templates/part/set/berserk.png"),
    "./templates/part/set/blessing.png": cv2.imread("./templates/part/set/blessing.png"),
    "./templates/part/set/bulwark.png": cv2.imread("./templates/part/set/bulwark.png"),
    "./templates/part/set/charge.png": cv2.imread("./templates/part/set/charge.png"),
    "./templates/part/set/command.png": cv2.imread("./templates/part/set/command.png"),
    "./templates/part/set/defense.png": cv2.imread("./templates/part/set/defense.png"),
    "./templates/part/set/efficacy.png": cv2.imread("./templates/part/set/efficacy.png"),
    "./templates/part/set/frenzy.png": cv2.imread("./templates/part/set/frenzy.png"),
    "./templates/part/set/haste.png": cv2.imread("./templates/part/set/haste.png"),
    "./templates/part/set/healing.png": cv2.imread("./templates/part/set/healing.png"),
    "./templates/part/set/leech.png": cv2.imread("./templates/part/set/leech.png"),
    "./templates/part/set/life.png": cv2.imread("./templates/part/set/life.png"),
    "./templates/part/set/morale.png": cv2.imread("./templates/part/set/morale.png"),
    "./templates/part/set/pierce.png": cv2.imread("./templates/part/set/pierce.png"),
    "./templates/part/set/precision.png": cv2.imread("./templates/part/set/precision.png"),
    "./templates/part/set/resolve.png": cv2.imread("./templates/part/set/resolve.png"),
    "./templates/part/set/revenge.png": cv2.imread("./templates/part/set/revenge.png"),
    "./templates/part/set/shock.png": cv2.imread("./templates/part/set/shock.png"),
    "./templates/part/set/strength.png": cv2.imread("./templates/part/set/strength.png"),
    "./templates/part/set/vengeful.png": cv2.imread("./templates/part/set/vengeful.png"),
    "./templates/part/set/zeal.png": cv2.imread("./templates/part/set/zeal.png"),
    "./templates/suboption/num/0.png": cv2.imread("./templates/suboption/num/0.png"),
    "./templates/suboption/num/1.png": cv2.imread("./templates/suboption/num/1.png"),
    "./templates/suboption/num/2.png": cv2.imread("./templates/suboption/num/2.png"),
    "./templates/suboption/num/3.png": cv2.imread("./templates/suboption/num/3.png"),
    "./templates/suboption/num/4.png": cv2.imread("./templates/suboption/num/4.png"),
    "./templates/suboption/num/5.png": cv2.imread("./templates/suboption/num/5.png"),
    "./templates/suboption/num/6.png": cv2.imread("./templates/suboption/num/6.png"),
    "./templates/suboption/num/7.png": cv2.imread("./templates/suboption/num/7.png"),
    "./templates/suboption/num/8.png": cv2.imread("./templates/suboption/num/8.png"),
    "./templates/suboption/num/9.png": cv2.imread("./templates/suboption/num/9.png"),
    "./templates/suboption/num/percent.png": cv2.imread("./templates/suboption/num/percent.png"),
    "./templates/suboption/text/attack.png": cv2.imread("./templates/suboption/text/attack.png"),
    "./templates/suboption/text/defence.png": cv2.imread("./templates/suboption/text/defence.png"),
    "./templates/suboption/text/speed.png": cv2.imread("./templates/suboption/text/speed.png"),
    "./templates/suboption/text/resist.png": cv2.imread("./templates/suboption/text/resist.png"),
    "./templates/suboption/text/hit.png": cv2.imread("./templates/suboption/text/hit.png"),
    "./templates/suboption/text/health.png": cv2.imread("./templates/suboption/text/health.png"),
    "./templates/suboption/text/crit.png": cv2.imread("./templates/suboption/text/crit.png"),
    "./templates/suboption/text/damage.png": cv2.imread("./templates/suboption/text/damage.png"),
    "./templates/suboption/text/chance.png": cv2.imread("./templates/suboption/text/chance.png"),
    "./templates/suboption/text/effect.png": cv2.imread("./templates/suboption/text/effect.png"),
}


masks = {
    "item_fullname": (1245, 148, 1768, 210),  # 장비 이름
    "item_portrait": (1265, 229, 1428, 388),  # 장비 초상화
    "mainoption_text": (1458, 245, 1637, 291),  # 장비 주옵
    "mainoption_num": (1524, 292, 1743, 353),  # 장비 주옵 숫자
    "suboption_1_text": (1274, 390, 1478, 431),  # 장비 부옵1
    "suboption_1_num": (1573, 390, 1755, 431),  # 장비 부옵1 숫자
    "suboption_2_text": (1274, 427, 1478, 469),  # 장비 부옵2
    "suboption_2_num": (1573, 427, 1755, 469),  # 장비 부옵2 숫자
    "suboption_3_text": (1274, 468, 1478, 509),  # 장비 부옵3
    "suboption_3_num": (1573, 468, 1755, 509),  # 장비 부옵3 숫자
    "suboption_4_text": (1274, 504, 1478, 546),  # 장비 부옵4
    "suboption_4_num": (1573, 504, 1755, 546),  # 장비 부옵4 숫자
}
